# frontend/Dockerfile
FROM node:22-alpine

WORKDIR /app

# Instalar dependencias primero (para aprovechar caché de Docker)
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto de Next.js
EXPOSE 3000

# Comando para desarrollo
CMD ["npm", "run", "dev"]